name: Continuous Integration

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]
    tags: [v*]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: ["ubuntu-latest"]
        # OS: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1
      - run: scala-cli compile .
